### ISSUE TITLE
bug in __repr__ dunder from GanjaScene class 

### ISSUE THREAD

**Issue by Dano-drevo** [pygae/pyganja#40]
```
>>> from pyganja import *
/usr/lib/python3/dist-packages/bpython/curtsiesfrontend/repl.py:251: UserWarning: Failed to import cef_gui, cef functions will be unavailable
  module = self.loader.load_module(name)
>>> gs = GanjaScene()
>>> gs
Traceback (most recent call last):
  File "<input>", line 1, in <module>
    gs
  File "/usr/local/lib/python3.6/dist-packages/pyganja/GanjaScene.py", line 105, in __repr__
    new_str = str.replace(new_str, ']}', """].map(x=>x.length=="""+str(self.mv_length)+"""?new Element(x):x)}""")
AttributeError: 'GanjaScene' object has no attribute 'mv_length'
```

**Comment by hugohadfield** [comment]
This is caused by mv_length only being set when a user adds a multivector object to the scene. Therefore if you try repr on a empty scene self.mv_length will not exist... Probably would be good to change this so that an empty scene just returns the string '[ ]' or something like that
